"""
CyberFusion XDR Enterprise - Cross-Domain XDR Correlation Engine
Correlates multi-domain detections across EDR, NDR, IAM, WAF, DLP, and Cloud
into consolidated unified incidents based on entity graphs, not raw timestamps alone.
"""
import time
import json
import uuid
from typing import Dict, Any, List, Optional
import logging

logger = logging.getLogger("cyberfusion.correlation")

# In-memory correlation state tracker: tenant_id -> list of active incident state dicts
# { incident_id, entities: {hosts, users, ips, hashes, domains}, tactics: set(), alert_ids: [], updated_at }
_ACTIVE_INCIDENT_GRAPHS: Dict[str, List[Dict[str, Any]]] = {}

class XDRCorrelationEngine:
    CORRELATION_WINDOW_SECONDS = 7200 # 2 hours temporal window for entity graph grouping

    @staticmethod
    def correlate_alert(alert: Dict[str, Any]) -> Dict[str, Any]:
        """
        Correlate an incoming alert against the entity graph.
        Returns:
            {"is_new": bool, "incident_id": str, "incident_payload": Dict[str, Any]}
        """
        tenant_id = alert.get("tenant_id", "tenant-enterprise-secops")
        mode = alert.get("mode", "LIVE")
        
        if tenant_id not in _ACTIVE_INCIDENT_GRAPHS:
            _ACTIVE_INCIDENT_GRAPHS[tenant_id] = []
        
        active_list = _ACTIVE_INCIDENT_GRAPHS[tenant_id]
        now = time.time()

        # Extract entities from the alert
        alert_hosts = {alert.get("affected_host")} if alert.get("affected_host") else set()
        alert_users = {alert.get("affected_user")} if alert.get("affected_user") else set()
        alert_ips = {ip for ip in [alert.get("source_ip"), alert.get("dest_ip")] if ip}
        
        matched_incident = None

        # Search for overlapping entity relationships within correlation window
        for inc in active_list:
            if inc.get("mode") != mode:
                continue
            if now - inc["updated_at"] > XDRCorrelationEngine.CORRELATION_WINDOW_SECONDS:
                continue
            
            # Check for entity intersection
            ent = inc["entities"]
            host_match = bool(alert_hosts.intersection(ent["hosts"]))
            user_match = bool(alert_users.intersection(ent["users"]))
            ip_match = bool(alert_ips.intersection(ent["ips"]))

            if host_match or user_match or ip_match:
                matched_incident = inc
                break

        if matched_incident:
            # Correlate into existing incident
            inc = matched_incident
            inc["entities"]["hosts"].update(alert_hosts)
            inc["entities"]["users"].update(alert_users)
            inc["entities"]["ips"].update(alert_ips)
            inc["alert_ids"].append(alert["alert_id"])
            if alert.get("mitre_tactic"):
                inc["tactics"].add(alert["mitre_tactic"])
            inc["updated_at"] = now
            
            # Upgrade severity if higher
            sev_weights = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}
            if sev_weights.get(alert["severity"], 1) > sev_weights.get(inc["severity"], 1):
                inc["severity"] = alert["severity"]

            logger.info(f"Cross-Domain Correlation: Alert {alert['alert_id']} merged into Incident {inc['incident_id']}")
            
            return {
                "is_new": False,
                "incident_id": inc["incident_id"],
                "incident_payload": inc
            }
        else:
            # Create a new correlated incident
            incident_id = f"INC-{int(now)}-{uuid.uuid4().hex[:6].upper()}"
            tactics = {alert["mitre_tactic"]} if alert.get("mitre_tactic") else set()
            
            new_inc = {
                "incident_id": incident_id,
                "tenant_id": tenant_id,
                "mode": mode,
                "title": f"Security Incident: {alert['title']}",
                "description": f"Multi-source correlation triggered by detection: {alert['description']}",
                "severity": alert["severity"],
                "status": "OPEN",
                "assignee": "SecOps Triage Queue",
                "entities": {
                    "hosts": alert_hosts,
                    "users": alert_users,
                    "ips": alert_ips
                },
                "tactics": tactics,
                "alert_ids": [alert["alert_id"]],
                "lead_alert_id": alert["alert_id"],
                "created_at": now,
                "updated_at": now,
                "sla_deadline": now + 14400 # 4 hour SLA
            }
            active_list.append(new_inc)
            
            logger.info(f"New Incident generated by correlation engine: {incident_id} [{alert['severity']}]")
            
            return {
                "is_new": True,
                "incident_id": incident_id,
                "incident_payload": new_inc
            }
